### ISSUE TITLE
블록익스플로러 블록해시에서 블록번호로 변수 변경.

### ISSUE THREAD

**Issue by magnalucus** [ethersocial/mist#1]
ethersocial.net/err404/block/블록번호 로 해야 링크가 가는데

현재

ethersocial.net/err404/block/블록해시 로 되어있음.

링크 변수를 블록해시에서 블록 변수로 변경.

**Comment by hackmod** [comment]
블록해시는 etherscan.io에서 지원합니다.
그리고 ETC explorer에서 블록 해시도 이제 지원합니다~
